# Generated by Django 2.1.7 on 2019-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trolleys',
            new_name='trolley',
        ),
    ]
